### ISSUE TITLE
Docs Roadmap

### ISSUE THREAD

**Issue by cufta22** [fosslytech/docs#38]
Near future plans for Docs.

### Features

- [ ] Impress - presentation editor
- [ ] Draw - simple drawing editor ( import/export will likey be a problem )

- [ ] Team integration
  - [ ] Team management ( create, delete, team, add, remove members )
  - [ ] Share documents with team

### Quality of life

- [ ] /doc keybinds ( ctrl + s... )
- [ ] Spotlight [component](https://mantine.dev/others/spotlight/), ( nav, recent docs... )

## Mobile App

- [ ] Expo project
- [ ] UI library

- [ ] Supabase integration
  - [ ] Auth ( login page, register -> open in web )
  - [ ] Try to reuse docs.fossly.tech/api

- [ ] TipTap editor integration
  - [ ] Writer
  - [ ] Calc
